name: CI Pipeline for Node.js

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     
      - name: Checkout code
        uses: actions/checkout@v3

     
      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '14' 
          cache: 'npm'

     
      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install --verbose

     
      - name: Run linter
        run: npm run lint

     
      - name: Run tests
        run: npm test

     
      - name: Build the project
        run: npm run build


