name: nodeJS CI/CD pipeline 

on:
  push:
    branches:
      - main

jobs:
  
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: node js setup
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Dependencies
        run: npm install

      #- name: run test
        #run: npm test
  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps: 

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

        
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-my:latest

      - name: Push Docker image
        run:  docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-my:latest

      - name: Run Docker container
        run: docker run -d --name nodejs-app-container ${{ secrets.DOCKER_USERNAME }}/nodejs-my:latest

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: ${{ secrets.EMAIL_USERNAME }}
          to: dina.manukyan7@gmail.com
          subject: "NodeJS |Docker image build | Docker container"
          body: " Hi :) The Docker image for nodejs-my was successfully built, pushed to Docker Hub, and the container is now running"
          
            
  
