name: nodeJS CI/CD pipeline

on:
  push:
    branches:
      -main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: node js setup
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Dependencies
        uses: npm install

      - name: run test
        uses: npm test
